import './globals.css'
import Header from './header'
import Modal from './modal'
import Providers from './providers/providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-screen min-h-screen h-fit bg-slate-900 text-gray-100 box-border overflow-x-hidden'>
      <Providers>
      <Header />
      <main className="min-h-3/5 w-screen">
          <Modal />
          {children} 
      </main>
      </Providers>
      </body>
    </html>
  )
}
